option(BUILD_SHARED_LIBS        "Build shared instead of static libraries."         OFF)
option(GR_BUILD_TESTS           "Build the unit tests."                             ON)
option(GR_BUILD_DOCS            "Build the Doxygen documentation."                  OFF)
option(GR_BUILD_EXAMPLES        "Build the example projects."                       OFF)
option(GR_BUILD_BENCHMARKS      "Build the performance benchmarks."                 OFF)
option(GR_WARNINGS_AS_ERRORS    "Treat compiler warnings as errors."                OFF)
