message(STATUS "------------------------ Configuration for Gravity ------------------------")
message(STATUS)
message(STATUS "CMake Generator:            ${CMAKE_GENERATOR}")
message(STATUS "Compiler:                   ${CMAKE_CXX_COMPILER_ID}")
message(STATUS "Compiler Version:           ${CMAKE_CXX_COMPILER_VERSION}")
message(STATUS "Build type:                 ${CMAKE_BUILD_TYPE}")
message(STATUS "CMAKE_INSTALL_PREFIX:       ${CMAKE_INSTALL_PREFIX}")
message(STATUS "C++ flags (General):        ${CMAKE_CXX_FLAGS}")
message(STATUS "C++ flags (Release):        ${CMAKE_CXX_FLAGS_RELEASE}")
message(STATUS "C++ flags (RelWithDebInfo): ${CMAKE_CXX_FLAGS_RELWITHDEBINFO}")
message(STATUS "C++ flags (Debug):          ${CMAKE_CXX_FLAGS_DEBUG}")
message(STATUS)
message(STATUS "GR_BUILD_TESTS:             ${GR_BUILD_TESTS}")
message(STATUS "GR_BUILD_DOCS:              ${GR_BUILD_DOCS}")
message(STATUS "GR_BUILD_EXAMPLES:          ${GR_BUILD_EXAMPLES}")
message(STATUS "GR_BUILD_BENCHMARKS:        ${GR_BUILD_BENCHMARKS}")
message(STATUS "GR_WARNINGS_AS_ERRORS:      ${GR_WARNINGS_AS_ERRORS}")
if (DEFINED BUILD_SHARED_LIBS)
    message(STATUS "BUILD_SHARED_LIBS:          ${BUILD_SHARED_LIBS}")
else ()
    message(STATUS "BUILD_SHARED_LIBS:          OFF")
endif ()
message(STATUS)
message(STATUS "GR Major Version:           ${CMAKE_PROJECT_VERSION_MAJOR}")
message(STATUS "GR Minor Version:           ${CMAKE_PROJECT_VERSION_MINOR}")
message(STATUS "GR Patch Version:           ${CMAKE_PROJECT_VERSION_PATCH}")
message(STATUS)
